apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: helm-trigger-set
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - cluster: local-cluster
            url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{cluster}}-todo-app'
      annotations:
        # 1. Dùng dấu * để bảo bot: "Soi tất cả các tag có trên Docker Hub cho tôi"
        argocd-image-updater.argoproj.io/image-list: todo-app=thien19012004/todo-app:*
        
        # 2. Dùng allow-tags để chặn tag rác: "Chỉ chấp nhận tag có định dạng số x.x.x"
        # Regex này sẽ lọc bỏ v1, latest, prod... chỉ giữ lại 0.1.11, 0.2.1, 1.0.0 v.v.
        argocd-image-updater.argoproj.io/todo-app.allow-tags: "^[0-9]+\\.[0-9]+\\.[0-9]+$"
        
        # 3. Giữ nguyên việc tách đôi tham số (CỰC KỲ QUAN TRỌNG để sạch Manifest)
        argocd-image-updater.argoproj.io/todo-app.helm.image-name: image.repository
        argocd-image-updater.argoproj.io/todo-app.helm.image-tag: image.tag
        
        argocd-image-updater.argoproj.io/todo-app.update-strategy: semver
        argocd-image-updater.argoproj.io/write-back-method: argocd
    spec:
      project: default
      source:
        repoURL: https://jfrog.ddthien.id.vn/artifactory/helm-local
        chart: todo-app
        targetRevision: '*'
        helm:
          passCredentials: true
      destination:
        server: '{{url}}'
        namespace: todo-app
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
  # 4. LÁ CHẮN: Chặn đứng việc ApplicationSet tự ý đè ngược lại chữ 'latest'
  ignoreApplicationDifferences:
  - jsonPointers:
    - /spec/source/helm/parameters