apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: helm-trigger-set
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - cluster: local-cluster
            url: https://kubernetes.default.svc
            version: 0.1.6 # Số này giờ chỉ để làm cảnh, vì dưới template mình dùng '*' rồi
  template:
    metadata:
      name: '{{cluster}}-todo-app'
      annotations:
        # Cấu hình ArgoCD Image Updater soi vào Docker Hub của bạn
        argocd-image-updater.argoproj.io/image-list: todo-app=docker.io/thien19012004/todo-app
        # Yêu cầu Updater ghi đè cái image.tag trong thư mục values.yaml của Helm
        argocd-image-updater.argoproj.io/todo-app.helm.image-spec: image.tag
        # Chiến lược chọn tag: Cứ bản nào số to nhất (Semantic Version) thì lấy
        argocd-image-updater.argoproj.io/todo-app.update-strategy: semver
        # Dùng Secret vừa tạo ở Bước 1 để tránh bị Docker Hub khóa vì Rate Limit
        argocd-image-updater.argoproj.io/todo-app.pull-secret: secret:argocd/dockerhub-creds
    spec:
      project: default
      source:
        repoURL: https://jfrog.ddthien.id.vn/artifactory/helm-local
        chart: todo-app
        targetRevision: '*'  # Luôn lấy Helm Chart mới nhất từ JFrog
        helm:
          passCredentials: true
      destination:
        server: '{{url}}'
        namespace: todo-app
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true