apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cr-trigger-set
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/Thien19012004/my-gitops-repo
        revision: HEAD
        directories:
          - path: custom-resources/*
  template:
    metadata:
      name: 'cr-{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/Thien19012004/my-gitops-repo
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: default