apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: helm-trigger-set
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - cluster: local-cluster
            url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{cluster}}-todo-app'
      annotations:
        # 1. Khai báo Image cần theo dõi (Bỏ docker.io/ để khớp với Helm)
        argocd-image-updater.argoproj.io/image-list: todo-app=thien19012004/todo-app
        
        # 2. TUYỆT CHIÊU: Tách riêng Repository và Tag để không bao giờ bị lỗi lặp tên Repo
        argocd-image-updater.argoproj.io/todo-app.helm.image-name: image.repository
        argocd-image-updater.argoproj.io/todo-app.helm.image-tag: image.tag
        
        # 3. Chiến lược lấy tag mới nhất và phương thức ghi đè trực tiếp
        argocd-image-updater.argoproj.io/todo-app.update-strategy: latest
        argocd-image-updater.argoproj.io/todo-app.pull-secret: secret:argocd/dockerhub-creds
        argocd-image-updater.argoproj.io/write-back-method: argocd
    spec:
      project: default
      source:
        repoURL: https://jfrog.ddthien.id.vn/artifactory/helm-local
        chart: todo-app
        targetRevision: '*'
        helm:
          passCredentials: true
      destination:
        server: '{{url}}'
        namespace: todo-app
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
  # 4. LÁ CHẮN: Chặn đứng việc ApplicationSet tự ý đè ngược lại chữ 'latest'
  ignoreApplicationDifferences:
  - jsonPointers:
    - /spec/source/helm/parameters