apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infra-trigger-set
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/Thien19012004/my-gitops-repo
        revision: HEAD
        directories:
          - path: infra/*
  template:
    metadata:
      name: 'infra-{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/Thien19012004/my-gitops-repo
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}' # Nó sẽ tự điền 'argocd' hoặc 'namespaces'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true