# efk-apps.yaml
---
apiVersion: v1
kind: Namespace
metadata:
  name: logging
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elasticsearch
  namespace: argocd
spec:
  project: default
  source:
    chart: elasticsearch
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 19.15.0
    helm:
      values: |
        image:
          tag: 8 # Ép dùng tag chính, bỏ qua tag r-revision lỗi
        global:
          storageClass: "local-path"
        master:
          replicaCount: 1
          resources:
            limits: { memory: 2Gi }
            requests: { cpu: 500m, memory: 2Gi }
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [CreateNamespace=true]

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluentd
  namespace: argocd
spec:
  project: default
  source:
    chart: fluentd
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 6.4.0
    helm:
      values: |
        image:
          tag: 1 # Dùng tag rolling 1.x.x của Bitnami
        aggregator:
          enabled: false
        forwarder:
          enabled: true
          configMap: "" # BUỘC PHẢI ĐỂ RỖNG để nó không đòi file fluentd-conf nữa
        elasticsearch:
          host: elasticsearch-master.logging.svc.cluster.local
          port: 9200
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated: { prune: true, selfHeal: true }

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kibana
  namespace: argocd
spec:
  project: default
  source:
    chart: kibana
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 10.3.0
    helm:
      values: |
        image:
          tag: 8 # Ép dùng tag chính cho Kibana
        elasticsearch:
          hosts: [ "elasticsearch-master.logging.svc.cluster.local" ]
          port: 9200
        service:
          type: NodePort
          ports: { http: 5601 }
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated: { prune: true, selfHeal: true }