apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-monitoring
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://prometheus-community.github.io/helm-charts'
    chart: kube-prometheus-stack
    targetRevision: 45.0.0
    helm:
      values: |
        alertmanager:
          config:
            global:
              resolve_timeout: 5m
              # Dùng file thay vì dán link trực tiếp để bảo mật
              slack_api_url_file: /etc/alertmanager/secrets/alertmanager-secrets/slack-url
              smtp_smarthost: 'smtp.gmail.com:587'
              smtp_from: 'ducthien19012004@gmail.com'
              smtp_auth_username: 'ducthien19012004@gmail.com'
              # Dùng file thay vì dán pass Gmail trực tiếp
              smtp_auth_password_file: /etc/alertmanager/secrets/alertmanager-secrets/smtp-password
              smtp_require_tls: true

            route:
              group_by: ['alertname', 'job']
              group_wait: 30s
              group_interval: 5m
              repeat_interval: 12h
              receiver: 'combined-receiver'
              routes:
                - match:
                    severity: critical
                  receiver: 'combined-receiver'
                  continue: true

            receivers:
            - name: 'combined-receiver'
              slack_configs:
              - channel: '#k8s-alerts'
                send_resolved: true
                title: '[{{ .Status | toUpper }}] K8s Alert'
                text: "Chi tiết lỗi: {{ range .Alerts }}{{ .Annotations.description }}\n{{ end }}"
              email_configs:
              - to: 'ducthienpa@gmail.com'
                send_resolved: true
          
          # Cấu hình quan trọng: Mount cái Secret vào Pod Alertmanager
          alertmanagerSpec:
            secrets:
              - alertmanager-secrets
            nodeSelector:
              type: infra-services

        prometheus:
          prometheusSpec:
            nodeSelector:
              type: infra-services
            retention: 1d
        
        grafana:
          nodeSelector:
            type: infra-services
          serviceMonitor:
            enabled: true
            labels:
              release: prometheus-monitoring
          ingress:
            enabled: true
            ingressClassName: nginx
            pathType: Prefix      
            hosts:
              - grafana.ddthien.id.vn
            path: /
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true