apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-monitoring
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://prometheus-community.github.io/helm-charts'
    chart: kube-prometheus-stack
    targetRevision: 45.0.0
    helm:
      values: |
        prometheus:
          prometheusSpec:
            nodeSelector:
              type: infra-services
            retention: 1d
        grafana:
          nodeSelector:
            type: infra-services
          serviceMonitor:
            enabled: true
            labels:
              release: prometheus-monitoring
          ingress:
            enabled: true
            ingressClassName: nginx
            pathType: Prefix      
            hosts:
              - grafana.ddthien.id.vn
            path: /
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true